### ISSUE TITLE
SQL Server connection error

### ISSUE THREAD

**Issue by sercanerhan** [Frank-Geisler/SQL-Server-Sample-Docker-Container#1]
connection string
`CMD /opt/mssql-tools/bin/sqlcmd -S`
cannot connect to database.

> Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
> Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2749.
> Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

Does sqlserver runs on startup? We did not define anything for that in Dockerfile (only used MS image).

**Comment by Frank-Geisler** [comment]
Hi sercanerhan!

Yes, SQL Server runs on startup. I think your command is missing some parameters. There is neither a server nor a user name given. Please refer to https://docs.microsoft.com/de-de/sql/tools/sqlcmd-utility?view=sql-server-2017 to see how the sqlcmd command is used.

Thank you and have a nice day

Frank
